PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "User" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "firstName" TEXT,
  "surname" TEXT,
  "mobile" TEXT UNIQUE,
  "email" TEXT NOT NULL UNIQUE,
  "role" TEXT NOT NULL DEFAULT 'STUDENT',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Student" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "userId" TEXT NOT NULL UNIQUE,
  "selectedSubjects" TEXT NOT NULL,
  "subjectTimelines" TEXT NOT NULL,
  "courseFee" INTEGER NOT NULL,
  "refundableDeposit" INTEGER NOT NULL,
  "totalPaid" INTEGER NOT NULL,
  "paymentStatus" TEXT NOT NULL DEFAULT 'WAITING_CONFIRMATION',
  "refundStatus" TEXT NOT NULL DEFAULT 'NOT_ELIGIBLE',
  "sincerityScore" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Enrollment" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "studentId" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "timelineDays" INTEGER NOT NULL,
  "startDate" DATETIME NOT NULL,
  "dueDate" DATETIME NOT NULL,
  "isLocked" BOOLEAN NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "SubjectPaper" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "subject" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "sampleAnswerUrl" TEXT,
  "marks" INTEGER NOT NULL DEFAULT 100,
  "publishedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Submission" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "studentId" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "paperTitle" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "checkedAnswerUrl" TEXT,
  "status" TEXT NOT NULL DEFAULT 'SUBMITTED',
  "marksAwarded" INTEGER,
  "sincereAttempt" BOOLEAN NOT NULL DEFAULT 0,
  "evaluatorNote" TEXT,
  "checkedAt" DATETIME,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "PaperAccess" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "studentId" TEXT NOT NULL,
  "subjectPaperId" TEXT NOT NULL,
  "canDownloadPaper" BOOLEAN NOT NULL DEFAULT 0,
  "canDownloadAnswer" BOOLEAN NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("subjectPaperId") REFERENCES "SubjectPaper" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE ("studentId", "subjectPaperId")
);

CREATE TABLE IF NOT EXISTS "DoubtRequest" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "studentId" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "channel" TEXT NOT NULL DEFAULT 'in-app',
  "status" TEXT NOT NULL DEFAULT 'open',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "OtpCode" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "userId" TEXT NOT NULL,
  "codeHash" TEXT NOT NULL,
  "expiresAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Session" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "userId" TEXT NOT NULL,
  "token" TEXT NOT NULL UNIQUE,
  "expiresAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

